version: '3.8'

services:
  database:
    container_name: postgres_nlw
    image: postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pg_certification